CREATE TABLE MOVIE (
    MOVIE_ID BIGINT NOT NULL AUTO_INCREMENT,
    MOVIE_TITLE VARCHAR(50) NOT NULL ,
    MOVIE_YEAR INT NOT NULL ,
    MOVIE_LANGUAGE VARCHAR(50) NOT NULL ,
    MOVIE_TYPE VARCHAR(20) NOT NULL ,
    CREATED_TIME BIGINT NOT NULL ,
    UPDATED_TIME BIGINT NOT NULL ,

    constraint MOVIE PRIMARY KEY (MOVIE_ID)
);

CREATE TABLE ARTIST (
    ARTIST_ID BIGINT NOT NULL AUTO_INCREMENT,
    ARTIST_NAME VARCHAR(50) NOT NULL ,
    CREATED_TIME BIGINT NOT NULL ,
    UPDATED_TIME BIGINT NOT NULL ,

    constraint ARTIST PRIMARY KEY (ARTIST_ID)
);

CREATE TABLE MOVIE_ROLES(
    ROLE_ID INT NOT NULL ,
    ROLE_NAME VARCHAR(50) NOT NULL ,
    ROLE_DESCRIPTION VARCHAR(200) NOT NULL ,
    CREATED_TIME BIGINT NOT NULL ,
    UPDATED_TIME BIGINT NOT NULL ,

    constraint MOVIE_ROLES PRIMARY KEY (ROLE_ID)
);

CREATE TABLE MOVIE_ARTISTS(
    ID BIGINT NOT NULL AUTO_INCREMENT ,
    MOVIE_ID BIGINT NOT NULL ,
    ARTIST_ID BIGINT NOT NULL ,
    ROLE_ID INT NOT NULL ,
    CREATED_TIME BIGINT NOT NULL ,
    UPDATED_TIME BIGINT NOT NULL ,

    constraint MOVIE_ARTISTS PRIMARY KEY (ID),
    constraint UNIQUE (MOVIE_ID , ARTIST_ID ),
    constraint MOVIE_ARTISTS_FK1 FOREIGN KEY ( MOVIE_ID ) references MOVIE( MOVIE_ID ) ON DELETE CASCADE ,
    constraint MOVIE_ARTISTS_FK2 FOREIGN KEY ( ARTIST_ID ) references ARTIST( ARTIST_ID ) ON DELETE CASCADE ,
    constraint MOVIE_ARTISTS_FK3 FOREIGN KEY ( ROLE_ID ) references MOVIE_ROLES( ROLE_ID ) ON DELETE CASCADE 
);
